# -*- coding: utf-8 -*-
"""SESI13_PEPPY PARHANI NOPIANTI_20230040139_PCD.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ostSucaUWDVu_CWjfa-pc7UliBJM3vl1
"""

!wget http://groups.csail.mit.edu/vision/LabelMe/NewImages/indoorCVPR_09.tar
!tar -xf indoorCVPR_09.tar

!ls

import glob
import cv2
import matplotlib.pyplot as plt


images = glob.glob("Images/*/*.jpg")
print("Jumlah gambar ditemukan:", len(images))


assert len(images) > 0, "Gambar tidak ditemukan!"

img_path = images[0]
print("Gambar dipakai:", img_path)

img = cv2.imread(img_path)
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

plt.imshow(img)
plt.title("Citra Asli - MIT Indoor")
plt.axis("off")

import numpy as np

key_text = input("Masukkan key enkripsi: ")
key = sum(ord(c) for c in key_text) % 256

encrypted = img ^ key

plt.imshow(encrypted)
plt.title("Citra Terenkripsi")
plt.axis("off")

key_text = input("Masukkan key dekripsi: ")
key = sum(ord(c) for c in key_text) % 256

decrypted = encrypted ^ key

plt.imshow(decrypted)
plt.title("Hasil Dekripsi")
plt.axis("off")

import cv2
encrypted_bgr = cv2.cvtColor(encrypted, cv2.COLOR_RGB2BGR)

cv2.imwrite("mit_encrypted.png", encrypted_bgr)
print("Gambar terenkripsi disimpan sebagai mit_encrypted.png")

decrypted_bgr = cv2.cvtColor(decrypted, cv2.COLOR_RGB2BGR)

cv2.imwrite("mit_decrypted.png", decrypted_bgr)
print("Gambar hasil dekripsi disimpan sebagai mit_decrypted.png")

import matplotlib.pyplot as plt

plt.figure(figsize=(15,5))

plt.subplot(1,3,1)
plt.imshow(img)
plt.title("Citra Asli")
plt.axis("off")

plt.subplot(1,3,2)
plt.imshow(encrypted)
plt.title("Citra Terenkripsi")
plt.axis("off")

plt.subplot(1,3,3)
plt.imshow(decrypted)
plt.title("Citra Hasil Dekripsi")
plt.axis("off")

plt.show()